---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Volunteer Work
- type: document
  path: SeafeastVideoEdits
  label: Video Editing for SeaFeast
- type: heading
  label: Resume
- type: document
  path: Resume
  label: Resume
- type: heading
  label: Curriculum Vitae (Education)
- type: document
  path: CV
  label: Curriculum Vitae
- type: heading
  label: Public Relations
- type: document
  path: SSI
  label: PR for the Salish Sea Institute
- type: heading
  label: Videos
- type: document
  path: soaringtowardsdecline
  label: Soaring towards decline
- type: document
  path: barleyforbeer
  label: Barley for Beer
- type: heading
  label: News Stories
- type: document
  path: testingwithaswab
  label: 'Fighting COVID with a swab: testing remains a vital weapon in saving lives'
- type: document
  path: toxictansyragwort
  label: Toxic Tansy Ragwort
- type: directory
  path: ''
  label: Directory
  create: all
  match: "**/*"
  templates:
  - content-feature
- type: document
  path: README-FORESTRY.md
  label: Help
  read_only: true
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.75.1
  preview_output_directory: public
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
